# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0928d88768115a26c496de569292d6fa9fca89499549718f4c523f49711750100749892f835796d0b0eca0b57731ac2adf51a34f889fb886272dcdc12992d1b6

test:
  secret_key_base: 9601e2b98f67b6cfe8fdf7489ac3361976f5913c3a686662b169cc8d22d312fb4510fb5c24b9ad33ee14cf1a8bda59be04101bb51c764b56e3fa5257117c0f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0928d88768115a26c496de569292d6fa9fca89499549718f4c523f49711750100749892f835796d0b0eca0b57731ac2adf51a34f889fb886272dcdc12992d1b6
#<%= ENV["SECRET_KEY_BASE"] %>
